<?php

namespace Repositories;

use Indoctrinated\Repository;
use Repositories\Translations\Bundle;
/**
 * Translations
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Translations extends Repository
{
    public static function bundle()
    {
        return new Bundle();
    }
}
